name: CI/CD Pipeline
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
      
      - name: Login to Amazon ECR
        run: aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 353925322836.dkr.ecr.eu-west-1.amazonaws.com
      
      # Build and push backend
      - name: Build backend Docker image
        run: docker build -t expense-tracker-backend:latest .
      
      - name: Tag backend image for ECR
        run: docker tag expense-tracker-backend:latest 353925322836.dkr.ecr.eu-west-1.amazonaws.com/expense-tracker-backend:latest
      
      - name: Push backend to ECR
        run: docker push 353925322836.dkr.ecr.eu-west-1.amazonaws.com/expense-tracker-backend:latest
      
      # Build and push frontend
      - name: Build frontend Docker image
        run: docker build -f frontend/Dockerfile -t expense-tracker-frontend:latest ./frontend
      
      - name: Tag frontend image for ECR
        run: docker tag expense-tracker-frontend:latest 353925322836.dkr.ecr.eu-west-1.amazonaws.com/expense-tracker-frontend:latest
      
      - name: Push frontend to ECR
        run: docker push 353925322836.dkr.ecr.eu-west-1.amazonaws.com/expense-tracker-frontend:latest